"""Pydantic API schemas."""
from app.schemas.customers import (
    CustomerNoteCreateRequest,
    CustomerNoteDeleteResponse,
    CustomerNoteResponse,
    CustomerTagAssignmentResponse,
    CustomerTagCreateRequest,
    CustomerTagCustomersResponse,
    CustomerListItemResponse,
    CustomerListResponse,
    CustomerTagDeleteResponse,
    CustomerTagListResponse,
    CustomerTagResponse,
    CustomerNoteUpdateRequest,
    CustomerProfileConversationResponse,
    CustomerProfileResponse,
    CustomerSummaryResponse,
    CustomerTagSummaryResponse,
    CustomerTagUpdateRequest,
    CustomerTimelineResponse,
)
from app.schemas.customer_duplicates import (
    CustomerDuplicateCandidateResponse,
    CustomerDuplicateListResponse,
    CustomerMergeRequest,
    CustomerMergeResponse,
)
from app.schemas.customer_segments import (
    CustomerSegmentCustomersResponse,
    CustomerSegmentDeleteResponse,
    CustomerSegmentListResponse,
    CustomerSegmentPreviewResponse,
    CustomerSegmentResponse,
    CustomerSegmentRuleRequest,
    CustomerSegmentRuleResponse,
    CustomerSegmentUpsertRequest,
)
from app.schemas.auth import LoginRequest, RefreshRequest, RoleResponse, TokenResponse, UserResponse
from app.schemas.facebook import (
    CurrentFacebookPageResponse,
    FacebookAuthUrlResponse,
    FacebookPageListResponse,
    FacebookPageResponse,
)

__all__ = [
    "CurrentFacebookPageResponse",
    "CustomerSegmentCustomersResponse",
    "CustomerSegmentDeleteResponse",
    "CustomerSegmentListResponse",
    "CustomerSegmentPreviewResponse",
    "CustomerSegmentResponse",
    "CustomerSegmentRuleRequest",
    "CustomerSegmentRuleResponse",
    "CustomerSegmentUpsertRequest",
    "CustomerNoteCreateRequest",
    "CustomerNoteDeleteResponse",
    "CustomerNoteResponse",
    "CustomerDuplicateCandidateResponse",
    "CustomerDuplicateListResponse",
    "CustomerMergeRequest",
    "CustomerMergeResponse",
    "CustomerTagAssignmentResponse",
    "CustomerTagCreateRequest",
    "CustomerTagCustomersResponse",
    "CustomerListItemResponse",
    "CustomerListResponse",
    "CustomerTagDeleteResponse",
    "CustomerTagListResponse",
    "CustomerTagResponse",
    "CustomerNoteUpdateRequest",
    "CustomerProfileConversationResponse",
    "CustomerProfileResponse",
    "CustomerSummaryResponse",
    "CustomerTagSummaryResponse",
    "CustomerTagUpdateRequest",
    "CustomerTimelineResponse",
    "FacebookAuthUrlResponse",
    "FacebookPageListResponse",
    "FacebookPageResponse",
    "LoginRequest",
    "RefreshRequest",
    "RoleResponse",
    "TokenResponse",
    "UserResponse",
]
